export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body> <h1>Menú</h1>
      <ul>
        <li>Opción 1</li>
        <li>Opción 2</li>
      </ul>
        {children}
        </body>
    </html>
  )
}
